### ISSUE TITLE
Where are you using features.cvs ?

### ISSUE THREAD

**Issue by FM-EC** [kevinpalm/walmart_sales_forecast#1]
Hi, I liked your implementation, I wonder, in which part of the code you use the features.csv to the markdown restrictions? 

 Thanks :)

**Comment by kevinpalm** [comment]
Hi, sorry for the bad documentation on this project. My group didn't use GitHub while we were developing our models, and in the end I just tossed the code up to store it somewhere.

But after a lot of experimentation, I didn't end up using features.csv in the final model as none of those features we improving my results. I'll go update the readme a little, I'd been meaning to clean up eventually anyways.
